language: node_js

branches:
  only:
  - master

before_script:
 - yarn global add react-scripts
script:
  - bash ./deploy.sh
sudo: false
node_js: '6'
cache:
  yarn: true
  directories:
  - node_modules
  - lib
  - lib-legacy
  - $HOME/.yarn-cache
